"""Request correlation: the trace id, the request id, and `Cache-Control`.

Authority: ``specs/15_API_SPEC.md`` sections 1.4 and 1.5.

`G8.7` asserts the trace header on a **failure**, which is the case the
implementation has to be built around. Starlette's middleware stack puts
``ServerErrorMiddleware`` outermost, so a response generated by the ``Exception``
handler is produced *outside* any user middleware -- a send-wrapper alone would
miss exactly the response the gate checks. The ids are therefore held in
context variables as well as on ``request.state``, and the error handlers read
them from there. Belt and braces, because the failure path is the one that
matters.
"""

from __future__ import annotations

import uuid
from collections.abc import Awaitable, Callable
from contextvars import ContextVar
from typing import Any, Final

from starlette.types import ASGIApp, Message, Receive, Scope, Send

__all__ = [
    "CASE_REVISION_HEADER",
    "REQUEST_ID_HEADER",
    "TRACE_ID_HEADER",
    "RequestContextMiddleware",
    "current_request_id",
    "current_trace_id",
    "new_uuid7",
]

TRACE_ID_HEADER: Final[str] = "X-Provenance-Trace-Id"
REQUEST_ID_HEADER: Final[str] = "X-Provenance-Request-Id"
CASE_REVISION_HEADER: Final[str] = "X-Provenance-Case-Revision"

_TRACE_ID: ContextVar[uuid.UUID | None] = ContextVar("pv_trace_id", default=None)
_REQUEST_ID: ContextVar[uuid.UUID | None] = ContextVar("pv_request_id", default=None)


def new_uuid7() -> uuid.UUID:
    """A time-ordered UUID.

    Section 1.3 prefers UUIDv7 so keyset pagination on ``(created_at, id)`` is
    stable. Python 3.12 has no ``uuid.uuid7``, so the layout is built here:
    48 bits of Unix milliseconds, version 7, 74 bits of randomness.
    """
    import os
    import time

    ms = int(time.time() * 1000) & ((1 << 48) - 1)
    rand = int.from_bytes(os.urandom(10), "big")
    value = (ms << 80) | (0x7 << 76) | ((rand >> 2) & ((1 << 74) - 1))
    value &= ~(0b11 << 62)
    value |= 0b10 << 62
    return uuid.UUID(int=value)


def current_trace_id() -> uuid.UUID:
    value = _TRACE_ID.get()
    return value if value is not None else new_uuid7()


def current_request_id() -> uuid.UUID:
    value = _REQUEST_ID.get()
    return value if value is not None else new_uuid7()


def _parse_supplied(raw: str | None) -> uuid.UUID | None:
    """Section 1.4: a caller-supplied trace id is ignored and replaced if
    malformed. It is never echoed back unvalidated -- an arbitrary header
    reflected into a response body is a small injection surface for free."""
    if not raw:
        return None
    try:
        return uuid.UUID(raw.strip())
    except (ValueError, AttributeError):
        return None


class RequestContextMiddleware:
    """Pure ASGI, so it also wraps responses produced by exception handlers
    inside the routing layer. Headers are only set when absent, so a handler
    that already emitted them wins."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        headers = {k.decode("latin-1").lower(): v.decode("latin-1") for k, v in scope["headers"]}
        trace_id = _parse_supplied(headers.get(TRACE_ID_HEADER.lower())) or new_uuid7()
        request_id = new_uuid7()

        trace_token = _TRACE_ID.set(trace_id)
        request_token = _REQUEST_ID.set(request_id)
        state: dict[str, Any] = scope.setdefault("state", {})
        state["trace_id"] = trace_id
        state["request_id"] = request_id

        async def send_wrapper(message: Message) -> None:
            if message["type"] == "http.response.start":
                raw = list(message.get("headers", []))
                present = {name.decode("latin-1").lower() for name, _ in raw}
                for name, value in (
                    (TRACE_ID_HEADER, str(trace_id)),
                    (REQUEST_ID_HEADER, str(request_id)),
                    ("Cache-Control", "no-store"),
                ):
                    if name.lower() not in present:
                        raw.append((name.encode("latin-1"), value.encode("latin-1")))
                message = {**message, "headers": raw}
            await send(message)

        try:
            await self.app(scope, receive, send_wrapper)
        finally:
            _TRACE_ID.reset(trace_token)
            _REQUEST_ID.reset(request_token)


#: Type of the ``call_next`` used by Starlette's BaseHTTPMiddleware. Declared
#: here so downstream modules can annotate without importing starlette
#: internals.
CallNext = Callable[[Any], Awaitable[Any]]
