"""The deterministic explanation read model.

Assembled by the control plane from committed rows only. Nothing here is
generated by a model, and no field accepts model prose.

Authority
---------
- ``specs/11_CONTRACTS.md`` section 14, whose code this module implements, and
  section 20.8.
- ``EXECUTION/70_TASK_PLAN.md`` T1.6, third sub-task, and section 2.3 -- the
  three-term vocabulary.

Grounding and lineage are two fields, never one
------------------------------------------------
:class:`BeliefProof` carries **``grounding``** -- the ``SUPPORTS`` /
``CONTRADICTS`` / ``QUALIFIES`` edge set, answering "why do you believe this"
-- and **``lineage``** -- the version chain, answering "what did you believe
before, and what changed your mind". They are separate fields under exactly
those two names and are never conflated: a changelog is not an argument, and
an argument is not a changelog.

Recorded deviations from section 14
-----------------------------------
1. **``LineageEntry.superseded_by_version_no`` is added**, optional. Section 14
   declares only ``superseded_by_version_id``, but ``EXECUTION/70_TASK_PLAN.md``
   T1.6 asks for the chain "with ``superseded_by_version_no``", and the wire
   shape in ``specs/15_API_SPEC.md``, the lineage table in
   ``frontend/30_UX_SPEC.md``, and the ``G8`` acceptance query in
   ``quality/23_PHASE_GATES.md`` all read ``superseded_by_version_no``. Both are
   carried so neither authority is contradicted. It is optional rather than
   required because section 20.8's own printed fixtures construct a superseded
   entry without it; when it *is* present it must be greater than
   ``version_no`` and must agree with the entry it points at.

2. **``StateTransitionProof`` is exported.** Section 14 defines the class and
   uses it as the type of ``StateProof.transitions``, but omits it from its
   ``__all__``. That is a spec typo; a field type that cannot be imported is
   not usable. Reported, and exported here.
"""

from __future__ import annotations

import uuid
from typing import Annotated

from pydantic import Field, JsonValue, StringConstraints, model_validator

from provenance_contracts.base import (
    BoundaryContract,
    Confidence,
    Contract,
    Money,
    ReasonCode,
    Revision,
    SafeIdentifier,
    Sha256Hex,
    UtcDatetime,
    Weight,
    content_hash,
    validate_half_open,
)
from provenance_contracts.ingestion import SourceLocator
from provenance_contracts.predicates import PredicateNode
from provenance_domain.enums import (
    AttentionLevel,
    CaseStatus,
    CaseType,
    CommitmentStatus,
    ConflictSeverity,
    ConflictStatus,
    ConflictType,
    EpistemicStatus,
    EvidenceType,
    MemoryMode,
    RetractionStatus,
    SubjectType,
    SupportRelation,
    SupportSourceKind,
    TransitionType,
    TriggerState,
    TriggerType,
    ValueType,
)

__all__ = [
    "PROOF_HASH_EXCLUDE",
    "BeliefProof",
    "BeliefVersionProof",
    "CaseSnapshot",
    "CommitmentProof",
    "ConflictProof",
    "DerivationTrace",
    "EvidenceProof",
    "FulfillmentProof",
    "GroundingEdgeProof",
    "LineageEntry",
    "StateProof",
    "StateTransitionProof",
    "TriggerProof",
]

Text = Annotated[str, StringConstraints(min_length=1, max_length=2000)]

#: Volatile fields excluded from ``proof_hash``, so the same committed state
#: hashes identically no matter when it was rendered.
PROOF_HASH_EXCLUDE: frozenset[str] = frozenset({"proof_id", "generated_at", "proof_hash"})


class EvidenceProof(Contract):
    """The immutable observation behind a grounding edge, with its locator.

    ``retraction_status`` is a full enum here, unlike ``EvidenceSnippet``: a
    State Proof must be able to *show* that a piece of evidence was retracted
    and that the belief it once supported has moved on. Hiding retractions from
    the proof would defeat the purpose of keeping lineage.
    """

    evidence_id: uuid.UUID
    artifact_id: uuid.UUID
    evidence_type: EvidenceType
    exact_text: Text | None = None
    normalized_text: Text
    source_locator: SourceLocator
    observed_at: UtcDatetime
    valid_from: UtcDatetime | None = None
    valid_to: UtcDatetime | None = None
    source_authority: Confidence | None = None
    retraction_status: RetractionStatus = RetractionStatus.ACTIVE
    artifact_received_at: UtcDatetime
    artifact_sender: Annotated[str, StringConstraints(max_length=320)] | None = None

    @model_validator(mode="after")
    def _validate_bounds(self) -> EvidenceProof:
        validate_half_open(self.valid_from, self.valid_to)
        return self


class GroundingEdgeProof(Contract):
    """One grounding edge, rendered.

    The relation is ``SUPPORTS``, ``CONTRADICTS`` or ``QUALIFIES``. This is the
    grounding half of the vocabulary; the version chain is
    :class:`LineageEntry` and lives under a different field.
    """

    support_id: uuid.UUID
    source_kind: SupportSourceKind
    source_id: uuid.UUID
    relation: SupportRelation
    weight: Weight | None = None
    reason_code: ReasonCode | None = None
    evidence: EvidenceProof | None = None
    claim_summary: Text | None = None

    @model_validator(mode="after")
    def _evidence_edges_carry_evidence(self) -> GroundingEdgeProof:
        if self.source_kind is SupportSourceKind.EVIDENCE and self.evidence is None:
            raise ValueError(
                "an EVIDENCE grounding edge must render its evidence; a proof that "
                "says 'trust me' is not a proof"
            )
        if self.evidence is not None and self.evidence.evidence_id != self.source_id:
            raise ValueError("rendered evidence does not match the edge source id")
        return self


class BeliefVersionProof(Contract):
    """The version currently standing for one proposition."""

    belief_version_id: uuid.UUID
    version_no: Annotated[int, Field(ge=1)]
    value_type: ValueType
    value_json: JsonValue
    epistemic_status: EpistemicStatus
    belief_confidence: Confidence
    valid_from: UtcDatetime | None = None
    valid_to: UtcDatetime | None = None
    recorded_at: UtcDatetime
    kernel_decision_id: uuid.UUID

    @model_validator(mode="after")
    def _validate_bounds(self) -> BeliefVersionProof:
        validate_half_open(self.valid_from, self.valid_to)
        return self


class LineageEntry(Contract):
    """One link in the version chain, with the reason it was replaced.

    Lineage without reasons is a changelog. Lineage with reason codes is an
    argument, which is what the user needs when a counterparty disputes it.

    ``superseded_by_version_no`` is the human-facing pointer the proof renders;
    ``superseded_by_version_id`` is the machine one. See recorded deviation 1.
    """

    belief_version_id: uuid.UUID
    version_no: Annotated[int, Field(ge=1)]
    value_json: JsonValue
    epistemic_status: EpistemicStatus
    valid_from: UtcDatetime | None = None
    valid_to: UtcDatetime | None = None
    recorded_at: UtcDatetime
    superseded_at: UtcDatetime | None = None
    superseded_by_version_id: uuid.UUID | None = None
    superseded_by_version_no: Annotated[int, Field(ge=2)] | None = None
    supersession_reason_code: ReasonCode | None = None
    kernel_decision_id: uuid.UUID

    @model_validator(mode="after")
    def _supersession_is_explained(self) -> LineageEntry:
        superseded = self.superseded_by_version_id is not None
        if superseded and self.supersession_reason_code is None:
            raise ValueError(f"version {self.version_no} was superseded without a reason code")
        if superseded and self.superseded_at is None:
            raise ValueError("a superseded version must record superseded_at")
        if self.superseded_by_version_no is not None:
            if not superseded:
                raise ValueError(
                    "superseded_by_version_no without superseded_by_version_id names "
                    "a successor the chain cannot resolve"
                )
            if self.superseded_by_version_no <= self.version_no:
                raise ValueError(
                    f"version {self.version_no} cannot be superseded by version "
                    f"{self.superseded_by_version_no}; the chain only moves forward"
                )
        validate_half_open(self.valid_from, self.valid_to)
        return self

    @property
    def is_current(self) -> bool:
        """True for the one open-ended entry: the version standing today."""
        return self.superseded_by_version_id is None


class DerivationTrace(Contract):
    """A deterministic computation shown with its inputs and its output."""

    derivation_name: SafeIdentifier
    function_version: Annotated[str, StringConstraints(pattern=r"^\d+\.\d+\.\d+$")]
    inputs: tuple[tuple[str, JsonValue], ...] = Field(default=(), max_length=20)
    output: JsonValue
    explanation: Text


class BeliefProof(Contract):
    """One proposition, its current version, its grounding, and its lineage.

    This model is the reason the three-term vocabulary exists. ``grounding``
    answers "why do you believe this"; ``lineage`` answers "what did you
    believe before, and what changed your mind".
    """

    belief_id: uuid.UUID
    subject_type: SubjectType
    subject_id: uuid.UUID
    subject_label: Annotated[str, StringConstraints(max_length=200)]
    predicate: SafeIdentifier
    current_version: BeliefVersionProof
    grounding: tuple[GroundingEdgeProof, ...] = Field(default=(), max_length=30)
    lineage: tuple[LineageEntry, ...] = Field(default=(), max_length=30)
    derivation: DerivationTrace | None = None

    @model_validator(mode="after")
    def _require_grounding(self) -> BeliefProof:
        """The read-side grounding invariant, checked at render time.

        If this ever fires in production it means a canonical belief exists
        that the system cannot justify, which is a data-integrity incident, not
        a rendering bug. Failing loudly here is the point.
        """
        if self.current_version.epistemic_status is EpistemicStatus.RETRACTED:
            return self
        if self.derivation is not None:
            return self
        supports = [e for e in self.grounding if e.relation is SupportRelation.SUPPORTS]
        if not supports:
            raise ValueError(
                f"belief {self.belief_id} ({self.predicate}) is canonical but "
                "UNGROUNDED: no SUPPORTS edge and no derivation"
            )
        return self

    @model_validator(mode="after")
    def _lineage_is_ordered_and_consistent(self) -> BeliefProof:
        versions = [entry.version_no for entry in self.lineage]
        if versions != sorted(versions):
            raise ValueError("lineage must be ordered oldest-first")
        if len(set(versions)) != len(versions):
            raise ValueError("duplicate version_no in lineage")
        if self.lineage:
            # Order matters, and it is the reverse of the order section 14
            # prints. A chain that stops short of the current version -- the
            # `stale_lineage` fixture in section 20.8 -- trips *both* checks,
            # and section 20.8 asserts the open-ends message. With section 14's
            # order the newest-entry check fires first and that printed test
            # can never see the message it asserts. Both checks are kept and
            # both stay reachable; only which one speaks first changed.
            open_ends = [e for e in self.lineage if e.superseded_by_version_id is None]
            if len(open_ends) != 1:
                raise ValueError("exactly one lineage entry may be un-superseded (the current one)")
            if self.current_version.version_no != max(versions):
                raise ValueError("current_version must be the newest entry in the lineage chain")
        return self

    @model_validator(mode="after")
    def _successor_pointers_agree(self) -> BeliefProof:
        """``superseded_by_version_no`` must name the version it points at.

        Two spellings of one pointer is two chances to drift; this is where
        they are made to agree, so the rendered chain and the id chain cannot
        tell different stories.
        """
        by_id: dict[uuid.UUID, int] = {
            entry.belief_version_id: entry.version_no for entry in self.lineage
        }
        by_id.setdefault(self.current_version.belief_version_id, self.current_version.version_no)
        for entry in self.lineage:
            if entry.superseded_by_version_no is None or entry.superseded_by_version_id is None:
                continue
            known = by_id.get(entry.superseded_by_version_id)
            if known is not None and known != entry.superseded_by_version_no:
                raise ValueError(
                    f"version {entry.version_no} names successor "
                    f"{entry.superseded_by_version_no} but the id it carries is "
                    f"version {known}"
                )
        return self

    @property
    def is_disputed(self) -> bool:
        return self.current_version.epistemic_status is EpistemicStatus.DISPUTED

    @property
    def contradicting_edges(self) -> tuple[GroundingEdgeProof, ...]:
        return tuple(e for e in self.grounding if e.relation is SupportRelation.CONTRADICTS)


class ConflictProof(Contract):
    """One contradiction, both sides rendered."""

    conflict_id: uuid.UUID
    conflict_type: ConflictType
    status: ConflictStatus
    severity: ConflictSeverity
    predicate: SafeIdentifier
    requires_human: bool
    left_summary: Text
    left_evidence: EvidenceProof | None = None
    right_summary: Text
    right_evidence: EvidenceProof | None = None
    canonical_belief_version_id: uuid.UUID | None = None
    resolution_reason_code: ReasonCode | None = None
    detected_at: UtcDatetime
    resolved_at: UtcDatetime | None = None


class FulfillmentProof(Contract):
    """One payment or delivery admitted against an obligation."""

    fulfillment_id: uuid.UUID
    evidence_id: uuid.UUID
    amount: Money | None = None
    fulfilled_at: UtcDatetime
    admission_status: Annotated[str, StringConstraints(max_length=32)]
    confidence: Confidence


class CommitmentProof(Contract):
    """One obligation, with the arithmetic shown rather than asserted."""

    commitment_id: uuid.UUID
    description: Text
    status: CommitmentStatus
    committed: Money | None = None
    fulfilled: Money | None = None
    outstanding: Money | None = None
    due_at: UtcDatetime | None = None
    fulfillments: tuple[FulfillmentProof, ...] = Field(default=(), max_length=30)
    outstanding_derivation: DerivationTrace | None = None

    @model_validator(mode="after")
    def _arithmetic_is_shown(self) -> CommitmentProof:
        if self.committed is None or self.outstanding is None:
            return self
        fulfilled = self.fulfilled
        if fulfilled is None:
            raise ValueError("a monetary obligation proof must show what was fulfilled")
        self.committed.require_same_currency(fulfilled)
        self.committed.require_same_currency(self.outstanding)
        if self.outstanding.amount != self.committed.amount - fulfilled.amount:
            raise ValueError(
                "outstanding shown in the proof is not derivable from committed - fulfilled"
            )
        if self.status is CommitmentStatus.FULFILLED and self.outstanding.amount > 0:
            raise ValueError("FULFILLED with outstanding > 0 cannot be rendered")
        if self.outstanding_derivation is None:
            raise ValueError(
                "a monetary obligation must show its derivation trace; the number "
                "the user acts on has to be explainable"
            )
        return self


class TriggerProof(Contract):
    """One armed predicate, with the term it will be judged against."""

    trigger_id: uuid.UUID
    trigger_type: TriggerType
    state: TriggerState
    predicate: PredicateNode
    not_before: UtcDatetime | None = None
    expires_at: UtcDatetime | None = None
    basis_case_revision: Revision
    last_evaluated_at: UtcDatetime | None = None
    last_result: Annotated[str, StringConstraints(max_length=32)] | None = None
    armed_because: Text


class CaseSnapshot(Contract):
    """The case as it stood at the revision this proof describes."""

    case_id: uuid.UUID
    case_type: CaseType
    title: Annotated[str, StringConstraints(max_length=300)]
    status: CaseStatus
    revision: Revision
    attention_level: AttentionLevel
    counterparty_name: Annotated[str, StringConstraints(max_length=200)]
    relationship_id: uuid.UUID
    opened_at: UtcDatetime
    resolved_at: UtcDatetime | None = None
    reopened_count: Annotated[int, Field(ge=0)]
    last_activity_at: UtcDatetime


class StateTransitionProof(Contract):
    """One recorded transition, rendered at the revision that produced it."""

    state_transition_id: uuid.UUID
    transition_type: TransitionType
    case_revision: Revision
    from_state: Annotated[str, StringConstraints(max_length=64)] | None = None
    to_state: Annotated[str, StringConstraints(max_length=64)] | None = None
    reason_code: ReasonCode
    recorded_at: UtcDatetime


class StateProof(BoundaryContract):
    """Everything Provenance can justify about one case, at one revision.

    Bound to the case revision: an action approved against this proof is
    invalidated the moment the revision moves. ``proof_hash`` lets a client
    detect that without re-reading the whole structure.
    """

    proof_id: uuid.UUID
    generated_at: UtcDatetime
    tenant_id: uuid.UUID
    user_id: uuid.UUID

    memory_mode: MemoryMode = MemoryMode.ON
    case: CaseSnapshot | None = None
    beliefs: tuple[BeliefProof, ...] = Field(default=(), max_length=60)
    conflicts: tuple[ConflictProof, ...] = Field(default=(), max_length=30)
    commitments: tuple[CommitmentProof, ...] = Field(default=(), max_length=30)
    triggers: tuple[TriggerProof, ...] = Field(default=(), max_length=20)
    transitions: tuple[StateTransitionProof, ...] = Field(default=(), max_length=60)
    derivations: tuple[DerivationTrace, ...] = Field(default=(), max_length=20)

    memory_disabled_reason: Text | None = None
    proof_hash: Sha256Hex | None = None

    @model_validator(mode="after")
    def _memory_off_is_empty(self) -> StateProof:
        """Addition A. A MemoryMode.OFF proof is a real, valid, empty proof.

        Judge Mode runs the identical artifact twice. With memory OFF there is
        no retrieval and no canonical state, so the honest rendering is an
        empty proof with a stated reason -- which is exactly why the OFF reply
        can only restate the invoice while the ON reply can say it contradicts
        the recorded termination.

        Emptiness is enforced rather than assumed, so a counterfactual cannot
        be quietly contaminated by leaked canonical state and still be
        presented as the memory-off baseline.
        """
        if self.memory_mode is MemoryMode.OFF:
            populated = any(
                (
                    self.beliefs,
                    self.conflicts,
                    self.commitments,
                    self.triggers,
                    self.transitions,
                )
            )
            if populated:
                raise ValueError(
                    "a MemoryMode.OFF proof must be empty; leaking canonical state "
                    "into the counterfactual makes the comparison meaningless"
                )
            if self.memory_disabled_reason is None:
                raise ValueError("MemoryMode.OFF requires memory_disabled_reason")
        else:
            if self.case is None:
                raise ValueError("a MemoryMode.ON proof must name its case")
            if self.memory_disabled_reason is not None:
                raise ValueError("memory_disabled_reason is only valid when mode is OFF")
        return self

    @model_validator(mode="after")
    def _transitions_do_not_exceed_current_revision(self) -> StateProof:
        if self.case is None:
            return self
        future = [t for t in self.transitions if t.case_revision > self.case.revision]
        if future:
            raise ValueError(
                "state proof contains transitions newer than the case revision it "
                "describes; the read was not point-in-time consistent"
            )
        return self

    def compute_hash(self) -> str:
        """Deterministic digest of the proof's substance.

        Excludes ``proof_id``, ``generated_at`` and ``proof_hash`` itself, so
        two renderings of the same committed revision agree. The Advocate binds
        a draft to this value; the executor re-computes it before sending.
        """
        return content_hash(self, exclude=PROOF_HASH_EXCLUDE)

    def with_hash(self) -> StateProof:
        return self.model_copy(update={"proof_hash": self.compute_hash()})

    def support_ids(self) -> frozenset[uuid.UUID]:
        """Every id a draft claim is permitted to cite.

        A claim citing anything outside this set is unsupported by definition.
        """
        ids: set[uuid.UUID] = set()
        for belief in self.beliefs:
            ids.add(belief.current_version.belief_version_id)
            for edge in belief.grounding:
                ids.add(edge.support_id)
                ids.add(edge.source_id)
                if edge.evidence is not None:
                    ids.add(edge.evidence.evidence_id)
        for conflict in self.conflicts:
            ids.add(conflict.conflict_id)
        for commitment in self.commitments:
            ids.add(commitment.commitment_id)
            for fulfillment in commitment.fulfillments:
                ids.add(fulfillment.fulfillment_id)
        return frozenset(ids)
